from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("source_type", models.CharField(choices=[("utility", "Utility"), ("travel", "Travel"), ("sap", "SAP")], max_length=20)),
                ("original_filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ActivityData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("source_type", models.CharField(choices=[("utility", "Utility"), ("travel", "Travel"), ("sap", "SAP")], max_length=20)),
                ("source_row_id", models.PositiveIntegerField()),
                ("date", models.DateField(blank=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ("unit_normalised", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(max_length=255)),
                ("scope", models.IntegerField(blank=True, choices=[(1, "Scope 1"), (2, "Scope 2"), (3, "Scope 3")], null=True)),
                ("status", models.CharField(choices=[("pending_review", "Pending Review"), ("approved", "Approved"), ("failed", "Failed")], default="pending_review", max_length=20)),
                ("suspicious_flag", models.BooleanField(default=False)),
                ("failure_reason", models.TextField(blank=True)),
                ("raw_data_link", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=100)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("modified_by", models.CharField(blank=True, max_length=100)),
                ("previous_scope", models.IntegerField(blank=True, null=True)),
                ("previous_status", models.CharField(blank=True, max_length=20)),
                ("upload_batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="prototype.uploadbatch")),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.CreateModel(
            name="ActivityAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("action", models.CharField(max_length=50)),
                ("actor", models.CharField(blank=True, max_length=100)),
                ("previous_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audits", to="prototype.activitydata")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SapRawRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("row_index", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("processed", "Processed"), ("failed", "Failed")], default="processed", max_length=20)),
                ("failure_reason", models.TextField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("matnr", models.CharField(blank=True, max_length=100)),
                ("maktx", models.CharField(blank=True, max_length=255)),
                ("menge", models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ("meins", models.CharField(blank=True, max_length=20)),
                ("werks", models.CharField(blank=True, max_length=100)),
                ("bsart", models.CharField(blank=True, max_length=50)),
                ("erdat", models.DateField(blank=True, null=True)),
                ("upload_batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saprawrows", to="prototype.uploadbatch")),
            ],
            options={"ordering": ["row_index"]},
        ),
        migrations.CreateModel(
            name="TravelRawRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("row_index", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("processed", "Processed"), ("failed", "Failed")], default="processed", max_length=20)),
                ("failure_reason", models.TextField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("trip_id", models.CharField(blank=True, max_length=100)),
                ("segment_type", models.CharField(blank=True, max_length=50)),
                ("departure_airport", models.CharField(blank=True, max_length=10)),
                ("arrival_airport", models.CharField(blank=True, max_length=10)),
                ("nights", models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ("distance_km", models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ("upload_batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="travelrawrows", to="prototype.uploadbatch")),
            ],
            options={"ordering": ["row_index"]},
        ),
        migrations.CreateModel(
            name="UtilityRawRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("row_index", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("processed", "Processed"), ("failed", "Failed")], default="processed", max_length=20)),
                ("failure_reason", models.TextField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meter_id", models.CharField(blank=True, max_length=100)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("usage_kwh", models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ("cost", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ("upload_batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="utilityrawrows", to="prototype.uploadbatch")),
            ],
            options={"ordering": ["row_index"]},
        ),
        migrations.AddIndex(model_name="activitydata", index=models.Index(fields=["tenant_id", "source_type"], name="prototype_a_tenant__1cc909_idx")),
        migrations.AddIndex(model_name="activitydata", index=models.Index(fields=["tenant_id", "status"], name="prototype_a_tenant__ff0e0a_idx")),
        migrations.AddIndex(model_name="activitydata", index=models.Index(fields=["tenant_id", "suspicious_flag"], name="prototype_a_tenant__27bd72_idx")),
    ]
