[phases.setup]
nixPkgs = ["python312Full", "nodejs_20"]

[phases.install]
cmds = [
  "python3 -m pip install -r backend/requirements.txt", 
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "python3 backend/manage.py collectstatic --noinput --settings=config.settings.production"
]

[start]
cmd = "cd backend && gunicorn config.wsgi:application"